# Generated by Django 5.1.6 on 2025-08-15 03:14

import datetime
import django.db.models.deletion
import times.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apunte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('subtitulo', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('orig_lan', models.CharField(max_length=2)),
                ('info', models.TextField()),
                ('pub_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookEntityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=512)),
                ('groupinfo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listname', models.CharField(max_length=500)),
                ('date_created', models.DateField(auto_now=True)),
                ('listinfo', models.TextField()),
                ('tipo', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CreditType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cuaderno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DiraBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=512)),
                ('pubyear', models.IntegerField()),
                ('pubdate', models.DateField(blank=True, null=True)),
                ('sinopsis', models.TextField()),
                ('idioma', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=75)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=times.models.path_and_name)),
                ('legacy', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DiraBunkoSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_title', models.CharField(max_length=512)),
                ('series_info', models.TextField()),
                ('series_type', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='DiraPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DiraSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=512)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('pais', models.CharField(max_length=128)),
                ('logo', models.ImageField(blank=True, max_length=255, null=True, upload_to=times.models.path_and_name)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('pais', models.CharField(max_length=128)),
                ('biographics', models.TextField(default='This section needs to be expanded.')),
            ],
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='mlbTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('nomina', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('info', models.TextField()),
                ('premiere', models.IntegerField()),
                ('runtime', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TimesMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('imgtype', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, max_length=255, null=True, upload_to=times.models.path_and_name)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrxTyp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=200)),
                ('codigo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('info', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WikiType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ApunteConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('media_type', models.CharField(max_length=100)),
                ('unidades', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('apunte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.apunte')),
            ],
        ),
        migrations.CreateModel(
            name='BookDuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_b', to='times.book')),
                ('right_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_b', to='times.book')),
                ('win_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='win_b', to='times.book')),
            ],
        ),
        migrations.CreateModel(
            name='BookEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etype', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=250)),
                ('info', models.TextField()),
                ('importancia', models.IntegerField(default=50)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.book')),
            ],
        ),
        migrations.CreateModel(
            name='BookGroupEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.bookentity')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.bookentitygroup')),
            ],
        ),
        migrations.CreateModel(
            name='BookMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgtype', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, max_length=255, null=True, upload_to=times.models.path_and_name)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.book')),
            ],
        ),
        migrations.CreateModel(
            name='BookQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.book')),
            ],
        ),
        migrations.CreateModel(
            name='BookTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=256)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.book')),
            ],
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages', models.IntegerField()),
                ('start_d', models.DateField()),
                ('finish_d', models.DateField()),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.book')),
            ],
        ),
        migrations.AddField(
            model_name='apunte',
            name='cuaderno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.cuaderno'),
        ),
        migrations.CreateModel(
            name='DiraBookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('contenido', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('edited_at', models.DateTimeField()),
                ('tipo', models.CharField(max_length=200)),
                ('importancia', models.IntegerField()),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.dirabook')),
            ],
        ),
        migrations.CreateModel(
            name='DiraBookTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=256)),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.dirabook')),
            ],
        ),
        migrations.CreateModel(
            name='DiraBunkoSeriesVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_title', models.CharField(max_length=500)),
                ('pubdate', models.DateField()),
                ('sinopsis', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.dirabunkoseries')),
            ],
        ),
        migrations.CreateModel(
            name='DiraBunkoSeriesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=500)),
                ('page_content', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
                ('importancia', models.IntegerField(default=100)),
                ('volume', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='times.dirabunkoseriesvolume')),
            ],
        ),
        migrations.CreateModel(
            name='DiraBunkoSeriesConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fec_ini', models.DateField()),
                ('fec_fin', models.DateField()),
                ('formato', models.CharField(max_length=25)),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.dirabunkoseriesvolume')),
            ],
        ),
        migrations.CreateModel(
            name='DiraConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fec_ini', models.DateField()),
                ('fec_fin', models.DateField(blank=True, null=True)),
                ('formato', models.CharField(max_length=150)),
                ('paginas', models.IntegerField()),
                ('idioma', models.CharField(max_length=150)),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.dirabook')),
            ],
        ),
        migrations.CreateModel(
            name='DiraOcupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupation', models.CharField(max_length=256)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.dirapersona')),
            ],
        ),
        migrations.AddField(
            model_name='dirabunkoseries',
            name='series_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.dirapersona'),
        ),
        migrations.CreateModel(
            name='DiraBookCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credito', models.CharField(max_length=256)),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.dirabook')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.dirapersona')),
            ],
        ),
        migrations.CreateModel(
            name='DiraBookSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.dirabook')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.diraseries')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('position', models.CharField(default='Not Specified', max_length=256)),
                ('number', models.IntegerField(default=0)),
                ('equ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.equipo')),
                ('jug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='LigaTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flagActivo', models.BooleanField(default=True)),
                ('equipoRel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.equipo')),
                ('ligaRel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.liga')),
            ],
        ),
        migrations.CreateModel(
            name='mlbGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('local_runs', models.IntegerField()),
                ('visit_runa', models.IntegerField()),
                ('comentarios', models.TextField()),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_team', to='times.mlbteam')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_team', to='times.mlbteam')),
            ],
        ),
        migrations.CreateModel(
            name='MovieCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.CharField(max_length=200)),
                ('persona', models.CharField(max_length=200)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieDuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_b', to='times.movie')),
                ('right_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_b', to='times.movie')),
                ('win_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='win_b', to='times.movie')),
            ],
        ),
        migrations.CreateModel(
            name='MoveListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.movie')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.movielist')),
            ],
        ),
        migrations.CreateModel(
            name='MovieMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgtype', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, max_length=255, null=True, upload_to=times.models.path_and_name)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wdate', models.DateField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('terminado', models.BooleanField(blank=True, default=False, null=True)),
                ('fase', models.CharField(max_length=120)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.liga')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elocal', to='times.equipo')),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evisita', to='times.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='matchSquad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.equipo')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.partido')),
            ],
        ),
        migrations.CreateModel(
            name='Goles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignado', models.IntegerField()),
                ('minuto', models.IntegerField()),
                ('adicional', models.IntegerField()),
                ('penal', models.BooleanField()),
                ('penales', models.BooleanField()),
                ('og', models.BooleanField(default=False)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.contrato')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.partido')),
            ],
        ),
        migrations.CreateModel(
            name='PartidoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm', models.TextField()),
                ('minuto', models.IntegerField(default=0)),
                ('tipo', models.IntegerField(default=0)),
                ('comm_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.partido')),
            ],
        ),
        migrations.CreateModel(
            name='Penales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignado', models.IntegerField()),
                ('anotado', models.BooleanField()),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.contrato')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.partido')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('avance', models.IntegerField(blank=True, default=0)),
                ('fecha_inicio', models.DateField()),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.book')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('progreso', models.IntegerField()),
                ('delta_lec', models.IntegerField(default=0)),
                ('barra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.progressbar')),
            ],
        ),
        migrations.CreateModel(
            name='RelBookList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.book')),
                ('blist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.booklist')),
            ],
        ),
        migrations.CreateModel(
            name='squadPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=1)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.contrato')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.matchsquad')),
            ],
        ),
        migrations.CreateModel(
            name='Trx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('desc', models.CharField(max_length=200)),
                ('debito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.cuenta')),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.trxtyp')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anho', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('mbudget', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.trxtyp')),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=100)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.tweet')),
            ],
        ),
        migrations.CreateModel(
            name='PageRels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.pagina')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.wiki')),
            ],
        ),
        migrations.CreateModel(
            name='MediaWiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.IntegerField()),
                ('media_id', models.IntegerField()),
                ('mwiki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.wiki')),
            ],
        ),
        migrations.CreateModel(
            name='ItemMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgtype', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, max_length=255, null=True, upload_to=times.models.path_and_name)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.wiki')),
            ],
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.IntegerField()),
                ('media_id', models.IntegerField()),
                ('ctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.credittype')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.wiki')),
            ],
        ),
        migrations.CreateModel(
            name='WikiPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgtype', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, max_length=255, null=True, upload_to=times.models.path_and_name)),
                ('wiki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.wiki')),
            ],
        ),
        migrations.AddField(
            model_name='wiki',
            name='wtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.wikitype'),
        ),
        migrations.AddField(
            model_name='book',
            name='wtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.wikitype'),
        ),
    ]
