# Generated by Django 5.1.6 on 2025-08-15 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiraTemporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_title', models.CharField(max_length=300)),
                ('single_season', models.BooleanField()),
                ('show_premiere', models.DateField()),
                ('show_finale', models.DateField()),
                ('episodes', models.IntegerField()),
                ('avg_duration', models.IntegerField()),
                ('tipo', models.CharField(max_length=50)),
                ('sinopsis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TempConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fec_ini', models.DateField()),
                ('fec_fin', models.DateField(blank=True, null=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.diratemporada')),
            ],
        ),
    ]
