# Generated by Django 5.1.6 on 2025-08-15 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0002_diratemporada_tempconsumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='RelShowCol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.diratemporada')),
                ('coleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.showcollection')),
            ],
        ),
    ]
