# Generated by Django 5.1.6 on 2025-08-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0003_showcollection_relshowcol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dirabunkoseriesconsumo',
            name='fec_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
