# Generated by Django 5.1.6 on 2025-08-22 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0004_alter_dirabunkoseriesconsumo_fec_fin'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiraBookPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato', models.CharField(max_length=250)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('fecha', models.DateField()),
                ('vendor', models.CharField(max_length=300)),
                ('libro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='times.dirabook')),
                ('volumen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='times.dirabunkoseriesvolume')),
            ],
        ),
    ]
