# Generated by Django 5.1.6 on 2025-04-25 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaSB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PaginaSB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpleblog.categoriasb')),
            ],
        ),
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attNombre', models.CharField(max_length=255)),
                ('attFecha', models.DateField(blank=True, null=True)),
                ('attEntero', models.IntegerField(blank=True, null=True)),
                ('attTexto', models.CharField(max_length=512)),
                ('attPagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_pagina', to='simpleblog.paginasb')),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='this_pagina', to='simpleblog.paginasb')),
            ],
        ),
    ]
