# Generated by Django 5.1.6 on 2025-04-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atributo',
            name='attDecimal',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atributo',
            name='attOrden',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
    ]
