# Generated by Django 5.1.6 on 2025-04-29 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleblog', '0002_atributo_attdecimal_atributo_attorden'),
    ]

    operations = [
        migrations.CreateModel(
            name='attrDecimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attNombre', models.CharField(max_length=255)),
                ('attValor', models.DecimalField(decimal_places=4, max_digits=16)),
                ('attOrden', models.IntegerField()),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpleblog.paginasb')),
            ],
        ),
        migrations.CreateModel(
            name='attrEntero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attNombre', models.CharField(max_length=255)),
                ('attValor', models.IntegerField()),
                ('attOrden', models.IntegerField()),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpleblog.paginasb')),
            ],
        ),
        migrations.CreateModel(
            name='attrFecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attNombre', models.CharField(max_length=255)),
                ('attValor', models.DateField()),
                ('attOrden', models.IntegerField()),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpleblog.paginasb')),
            ],
        ),
        migrations.CreateModel(
            name='attrPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attNombre', models.CharField(max_length=255)),
                ('attOrden', models.IntegerField()),
                ('attValor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_pagina', to='simpleblog.paginasb')),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='this_pagina', to='simpleblog.paginasb')),
            ],
        ),
        migrations.CreateModel(
            name='attrTexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attNombre', models.CharField(max_length=255)),
                ('attValor', models.TextField()),
                ('attOrden', models.IntegerField()),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpleblog.paginasb')),
            ],
        ),
        migrations.DeleteModel(
            name='Atributo',
        ),
    ]
