# Generated by Django 5.1.6 on 2025-04-29 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleblog', '0003_attrdecimal_attrentero_attrfecha_attrpagina_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemColeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RelacionIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpleblog.itemcoleccion')),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpleblog.paginasb')),
            ],
        ),
    ]
