# Generated by Django 5.1.6 on 2025-04-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleblog', '0004_itemcoleccion_relacionic'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginasb',
            name='fecha_inicio',
            field=models.DateField(default='2025-04-29'),
        ),
    ]
